### ISSUE TITLE
SBU train error

### ISSUE THREAD

**Issue by li-Yongpeng** [stevewongv/DSC-PyTorch#11]
Hi! thanks for your excellent work! When I train the model using SBU dataset, I got this problem. My torch version is 1.4.0 and cuda version is 10.0. The following is error message:

Traceback (most recent call last):
  File "/home/lyp/PycharmProjects/DSC-PyTorch/main.py", line 307, in <module>
    run_train_val(args.model)
  File "/home/lyp/PycharmProjects/DSC-PyTorch/main.py", line 260, in run_train_val
    sess.save_mask(sess.log_name, [batch_t['image'],  batch_t['B'],pred_t])
  File "/home/lyp/PycharmProjects/DSC-PyTorch/main.py", line 211, in save_mask
    tmp_list = [data[idx], label[idx],predict_4[idx], predict_3[idx], predict_2[idx], predict_1[idx], predict_0[idx], predict_g[idx], predict_f[idx]]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by stevewongv** [comment]
Please follow the requirements!
